wget -c http://www.esworldcup.com/img/flags/100x66/AD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AQ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/AZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BB.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BJ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/BZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/CZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DJ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/DZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/EC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/EE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/EG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/EH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ER.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ES.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ET.gif
wget -c http://www.esworldcup.com/img/flags/100x66/EU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FJ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/FR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GB.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GQ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/GY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/HU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ID.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IQ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/IT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/JE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/JM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/JO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/JP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/KZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LB.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/LY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ML.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MQ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MX.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/MZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/NZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/OM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/PY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/QA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/RE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/RO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/RU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/RW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SB.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SL.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ST.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/SZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TD.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TF.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TH.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TJ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TO.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TP.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TT.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TV.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TW.gif
wget -c http://www.esworldcup.com/img/flags/100x66/TZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UK.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/US.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UY.gif
wget -c http://www.esworldcup.com/img/flags/100x66/UZ.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VC.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VG.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VI.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VN.gif
wget -c http://www.esworldcup.com/img/flags/100x66/VU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/WS.gif
wget -c http://www.esworldcup.com/img/flags/100x66/YE.gif
wget -c http://www.esworldcup.com/img/flags/100x66/YU.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ZA.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ZM.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ZR.gif
wget -c http://www.esworldcup.com/img/flags/100x66/ZW.gif
